[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip

board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    https://github.com/SUPLA/supla-device.git#v26.9.2
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306

build_flags =
    -D CORE_DEBUG_LEVEL=0
